name: Deploy Pages

on:
  push:
    branches:
      - master-hyx3179
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          wget -q https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20220405/closure-compiler-v20220405.jar -O ./compiler.jar
          mkdir ./public
          java -jar compiler.jar --js kitten-scientists.user.js --js_output_file ./public/kitten-scientists.user.js
          wget -q https://hyx3179.github.io/scientists/ks.version.json -O ./public/ks.version.json
          node generate-buildver.js
          cp ./updateLog.html ./public
          cp -r ./public ./public_Netlify
          echo -e '/*\n  Access-Control-Allow-Origin: *' > ./public_Netlify/_headers

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Deploy Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          npm install netlify-cli -g
          netlify deploy --dir=public_Netlify --prod