name: Deploy Pages

on:
  push:
    branches:
      - master-hyx3179
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: |
          npm i -g google-closure-compiler
          mkdir ./public
          google-closure-compiler --js ./kitten-scientists.user.js --js_output_file ./public/kitten-scientists.user.js
          wget -q https://${DEPLOY_URL}/scientists/ks.version.json -O ./public/ks.version.json
          node generate-buildver.js
          cp ./updateLog.html ./public

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}